language: rust
rust:
  - stable
  - beta
  - nightly
 

script:
  - cargo build
  - cargo test

matrix:
  allow_failures:
    - rust: nightly
    - rust: beta # clippy currently has a bug on beta
  fast_finish: true
